openapi: 3.0.3
info:
  title: Goa SNMP Service
  description: Service for walking snmp trees and converting to http
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for goa-snmp
paths:
  /hosts:
    get:
      tags:
      - goa-snmp
      summary: list goa-snmp
      operationId: goa-snmp#list
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostCollection'
              example:
              - on_demand: true
                public: true
              - on_demand: true
                public: true
              - on_demand: true
                public: true
  /hosts/{Hostname}:
    post:
      tags:
      - goa-snmp
      summary: add goa-snmp
      operationId: goa-snmp#add
      parameters:
      - name: Hostname
        in: path
        description: Hostname or Ip of Device
        required: true
        schema:
          type: string
          description: Hostname or Ip of Device
          example: Impedit soluta tempore hic.
        example: Doloremque qui atque dolorem nulla.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OnDemand:
                  type: boolean
                  description: Whether or not Ondemand polling is supported
                  example: false
                Public:
                  type: boolean
                  description: Whether or not to walk public tree
                  example: false
              example:
                OnDemand: true
                Public: false
            example:
              OnDemand: false
              Public: false
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoasnmpHost'
              example:
                on_demand: false
                public: false
  /openapi.json:
    get:
      tags:
      - goa-snmp
      summary: Download ./gen/http/openapi.json
      operationId: goa-snmp#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    GoasnmpHost:
      type: object
      properties:
        on_demand:
          type: boolean
          description: Whether or not Ondemand polling is supported
          example: false
        public:
          type: boolean
          description: Whether or not to walk public tree
          example: true
      description: Host to be queried
      example:
        on_demand: false
        public: false
    HostCollection:
      type: array
      items:
        $ref: '#/components/schemas/GoasnmpHost'
      example:
      - on_demand: true
        public: true
      - on_demand: true
        public: true
      - on_demand: true
        public: true
